# Numpy :(Numerical python) Act as a :  FOUNDATION FOR  DATA SCIENCE

- Numpy is a python library/package for mathematical computing and processing multi dimensional array.
- It is written in C 
- It overcomes the prpblem of running slower algorithms on python by using multi dimensional arrays and functions that operate on arrays.
- Any algorithm that can be expressed as function on arrays, allow us to execute te algorithms to be run quickly.



# Numpy Features:
- Powerful tool for handling large amount of data using ndarry in terms of computation speed and memory.
- executes element wise operations and mathematical calculations in a very efficient manner 
- provides efficient way to store and manipulating the data
- performs linear algebra,fourier transform or any complex operations very conviniently.

# the core data structure of numpy is ndarray


## numpy Applications :

- Used in Data science to handle vast amount of data and process it efficiently in terms of resource and time.

- Used in Deep learning where images are presented in the form of pixel then we make it array or matrix to perform any operation on it to get useful information 

# ARRAY :

- stores homegeneous data 
- only be numbers (int,float,complex) #note : It can store the  string data but not used that way.
- Fast and efficient
- supports various mathematical functions.


In [1]:
d=[400,300,100,200]  ## input
sp=[40,50,70,60]  ## input
# t=[10,6,1.42,3.33]  ## output

In [2]:
# using zip

In [3]:
# using len

In [4]:
# using map

In [5]:
import numpy as np

In [6]:
d=[400,300,100,200]  ## input
sp=[40,50,70,60]  ## input


d1=np.array(d)
s1=np.array(sp)
print(type(d1))
# t=[10,6,1.42,3.33]  ## output

<class 'numpy.ndarray'>


In [7]:
d1/s1

array([10.        ,  6.        ,  1.42857143,  3.33333333])

In [8]:
d/sp

TypeError: unsupported operand type(s) for /: 'list' and 'list'

# how to create a array
- list
- tuple
- scalor
- numpy function

In [2]:
import numpy as np

# from list

# 1 d

In [3]:
a=np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

# 2 d

In [4]:
a=np.array([[1,2,3,4,5],[6,7,8,6,7]])
print(a)
type(a)

[[1 2 3 4 5]
 [6 7 8 6 7]]


numpy.ndarray

# from tuple

# 2 d

In [5]:
a=np.array(((1,2,3,4,5),(6,7,8,6,7)))
print(a)
type(a)

[[1 2 3 4 5]
 [6 7 8 6 7]]


numpy.ndarray

# from scalor

In [18]:
a=np.array(6)
print(a)
type(a)

6


numpy.ndarray

In [19]:
a

array(6)

# array properties
- ndim
- shape
- size
- dtype
- itemsize

# ndim: it tells the number of dimension
# note: open brackets in starting

In [21]:
# 1 d
a=np.array([1,2,3])
print(a)
a.ndim

[1 2 3]


1

In [22]:
# 2 d
a=np.array([[1,2,3],[1,2,3]])
print(a)
a.ndim

[[1 2 3]
 [1 2 3]]


2

In [23]:
# 3 d
a=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(a)
a.ndim

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


3

In [9]:
# 4 d
a=np.array([[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]],[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]])
print(a)
a.ndim

[[[[1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]]]


 [[[1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]]]]


4

In [27]:
# 5 d
a=np.array([[[[[1,2,3]]]]])
print(a)
a.ndim

[[[[[1 2 3]]]]]


5

In [28]:
# 10 d
a=np.array([[[[[[[[[[1,2,3]]]]]]]]]])
print(a)
a.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [30]:
np.array([[[[[[[[[[1,2,3]]]]]]]]]]).ndim

10

# shape : it tells the number of elements in each dimension

In [10]:
a=np.array([2,20,12,101])
print(a.ndim)
a.shape

1


(4,)

In [11]:
a=np.array([[2,20,12,101],[12,120,112,10]])
print(a.ndim)
a.shape

2


(2, 4)

In [12]:
a=np.array([[1,5,4,5,6,7]])
print(a.ndim)
a.shape

2


(1, 6)

In [13]:
a=np.array([[[1],[9],[90]]])
print(a.ndim)
print(a.shape)

3
(1, 3, 1)


# task: 3,4,1

In [14]:
a=np.array([[[1],[2],[5],[6]],[[7],[8],[93],[6]],[[6],[8],[8],[8]]])

In [15]:
a

array([[[ 1],
        [ 2],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [93],
        [ 6]],

       [[ 6],
        [ 8],
        [ 8],
        [ 8]]])

In [16]:
a.ndim

3

In [18]:
a.shape

(3, 4, 1)

# dtype: it tells the type of each element in the array

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
a


array([1, 2, 3, 4])

In [4]:
a.dtype

dtype('int32')

# size: tells the total numbers of elements in the array

In [5]:
a=np.array([[1,2,3,4],[1,2,3,4]])
a.shape

(2, 4)

In [6]:
a.size

8

# itemsize: tells the memory occupied by each element of the array in bytes

In [7]:
a.itemsize

4

In [8]:
a.dtype

dtype('int32')

# difference between array and list

-  Array Performs direct operation on array gives more comfort to handle operations
-  Arrays are faster than list  
-  Array takes less resource(memory)
- data stored in contigious memory than list thats why array as faster

In [2]:
import sys
import numpy as np
l=list(range(100))
a=np.arange(100)
print(sys.getsizeof(l))
print(a.itemsize)
print("list takes :",sys.getsizeof(l)*len(l),"bytes")  ##ys.getsizeof(l) : size of each element in the list
print("array takes : ",a.itemsize*a.size,"bytes" ) ## itemsize: size of each element in the array.


856
4
list takes : 85600 bytes
array takes :  400 bytes


# indexing and slicing

# 1 d

In [3]:
a=np.array([12,3,5,6,7,8,10,-1,45,56,78,90])
print(a)

[12  3  5  6  7  8 10 -1 45 56 78 90]


# indexing 

In [4]:
a[6]

10

# or

In [5]:
a[-6]

10

In [6]:
a[100]

IndexError: index 100 is out of bounds for axis 0 with size 12

# slicing 

In [7]:
a

array([12,  3,  5,  6,  7,  8, 10, -1, 45, 56, 78, 90])

In [8]:
a[3:7]

array([ 6,  7,  8, 10])

In [9]:
a[-4:]

array([45, 56, 78, 90])

In [10]:
a[:-2]

array([12,  3,  5,  6,  7,  8, 10, -1, 45, 56])

In [11]:
a[2:-2:2]

array([ 5,  7, 10, 45])

In [12]:
a[::-1]

array([90, 78, 56, 45, -1, 10,  8,  7,  6,  5,  3, 12])

In [13]:
a[2::2]

array([ 5,  7, 10, 45, 78])

In [14]:
a

array([12,  3,  5,  6,  7,  8, 10, -1, 45, 56, 78, 90])

# fetch 3,5,10,45,78 # discontinous form: fancy indexing

In [15]:
a[[1,2,6,8,10]]

array([ 3,  5, 10, 45, 78])

# indexing and slicing on 2 d 

In [16]:
a=np.array([[12,3,4,5,6],[1,0,40,50,60],[120,30,-4,23,61],[0,8,27,28,29]])
a

array([[ 12,   3,   4,   5,   6],
       [  1,   0,  40,  50,  60],
       [120,  30,  -4,  23,  61],
       [  0,   8,  27,  28,  29]])

# indexing

In [17]:
a[1]

array([ 1,  0, 40, 50, 60])

# or

In [18]:
a[-3]

array([ 1,  0, 40, 50, 60])

In [19]:
a[10]

IndexError: index 10 is out of bounds for axis 0 with size 4

In [20]:
a[-4]

array([12,  3,  4,  5,  6])

# slicing 

In [21]:
a[0::2]

array([[ 12,   3,   4,   5,   6],
       [120,  30,  -4,  23,  61]])

In [22]:
a[-2:]

array([[120,  30,  -4,  23,  61],
       [  0,   8,  27,  28,  29]])

In [23]:
a[:-1]

array([[ 12,   3,   4,   5,   6],
       [  1,   0,  40,  50,  60],
       [120,  30,  -4,  23,  61]])

# fetch 40

In [24]:
a[1][2]

40

# or

In [25]:
a[1,2]

40

In [26]:
a[:,1::2]

array([[ 3,  5],
       [ 0, 50],
       [30, 23],
       [ 8, 28]])

In [27]:
a[-2:,1:]

array([[30, -4, 23, 61],
       [ 8, 27, 28, 29]])

In [28]:
a[1:,1:-1]

array([[ 0, 40, 50],
       [30, -4, 23],
       [ 8, 27, 28]])

In [29]:
a[:,-2:]

array([[ 5,  6],
       [50, 60],
       [23, 61],
       [28, 29]])

In [30]:
a[2,0::2]

array([120,  -4,  61])

In [31]:
a[[0,0,1,3],[1,2,3,4]]

array([ 3,  4, 50, 29])

# 3d 

In [32]:
a=np.array([[[12,34,5],[132,334,53,]],[[112,314,51],[32,34,5,]]])
a

array([[[ 12,  34,   5],
        [132, 334,  53]],

       [[112, 314,  51],
        [ 32,  34,   5]]])

In [33]:
a[0]

array([[ 12,  34,   5],
       [132, 334,  53]])

In [34]:
a[1]

array([[112, 314,  51],
       [ 32,  34,   5]])

In [35]:
a[1][1][1]

34

# traversal on array

In [10]:
a=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
a

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [11]:
for i in a:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4


# or

In [12]:
for i in np.nditer(a):
    print(i)

1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4


# filtering in array

In [38]:
marks=np.array([[23,56,89,3,98,12],[23,56,89,3,98,12]])
marks

array([[23, 56, 89,  3, 98, 12],
       [23, 56, 89,  3, 98, 12]])

# fetch those marks 50

In [19]:
marks>50

array([[False,  True,  True, False,  True, False],
       [False,  True,  True, False,  True, False]])

In [20]:
marks[marks>50] # masking

array([56, 89, 98, 56, 89, 98])

In [23]:
marks[(marks>50)==False] # masking

array([23,  3, 12, 23,  3, 12])

# if else: where

# where
- it returns the index where particular condition met
- it works as if else

In [39]:
marks

array([[23, 56, 89,  3, 98, 12],
       [23, 56, 89,  3, 98, 12]])

In [26]:
np.where(marks>50)

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([1, 2, 4, 1, 2, 4], dtype=int64))

In [27]:
np.where(marks>50,"pass","fail")

array([['fail', 'pass', 'pass', 'fail', 'pass', 'fail'],
       ['fail', 'pass', 'pass', 'fail', 'pass', 'fail']], dtype='<U4')

# fail: even odd

In [40]:
np.where(marks>50,"pass",np.where(marks%2==0,"even-fail","odd-fail"))

array([['odd-fail', 'pass', 'pass', 'odd-fail', 'pass', 'even-fail'],
       ['odd-fail', 'pass', 'pass', 'odd-fail', 'pass', 'even-fail']],
      dtype='<U9')

# some initialization

- zeros
- ones
- empty
- full

In [42]:
np.zeros([3,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
np.ones([3,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
np.empty([5,4],dtype=int)

array([[-1, -1,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [45]:
np.full([5,4],9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

# task : create an array of 5,5 : in which borders are ones and rest are zeros

In [46]:
n=int(input("enter the size "))
a=np.ones([n,n])
a

enter the size  5


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# linspace: (start,end,number of elements) , where end is inclusive
# arange:(start,end,stepsize): end is exclusive

# arange: same as range 

In [48]:
np.arange(1,30,6)

array([ 1,  7, 13, 19, 25])

In [49]:
np.linspace(1,30,6)

array([ 1. ,  6.8, 12.6, 18.4, 24.2, 30. ])

# copy and view 

In [6]:
a=np.array([[12,34,5,67],[112,314,5161,7]])
a

array([[  12,   34,    5,   67],
       [ 112,  314, 5161,    7]])

In [7]:
print(a)
a1=a.copy() #deep copy
print(a1)
print("\n")
a1[1,-1]=700
print(a1)
print(a)

[[  12   34    5   67]
 [ 112  314 5161    7]]
[[  12   34    5   67]
 [ 112  314 5161    7]]


[[  12   34    5   67]
 [ 112  314 5161  700]]
[[  12   34    5   67]
 [ 112  314 5161    7]]


In [8]:
print(a)
a1=a.view() #shallow copy
print(a1)
print("\n")
a1[1,-1]=700
print(a1)
print(a)

[[  12   34    5   67]
 [ 112  314 5161    7]]
[[  12   34    5   67]
 [ 112  314 5161    7]]


[[  12   34    5   67]
 [ 112  314 5161  700]]
[[  12   34    5   67]
 [ 112  314 5161  700]]


# reshaping:

we can reshape 2,6 into : 

- 3,4
- 4,3
- 1,12,
- 12,1
- 1,6,2
etc


- reshape: deep copy 
- resize : shallow copy

In [53]:
a=np.array([[12,3,4,5,6,10],[112,13,114,15,6,110]])
a

array([[ 12,   3,   4,   5,   6,  10],
       [112,  13, 114,  15,   6, 110]])

In [54]:
a.shape

(2, 6)

In [55]:
a.reshape([5,6])

ValueError: cannot reshape array of size 12 into shape (5,6)

In [56]:
a.reshape([3,4])

array([[ 12,   3,   4,   5],
       [  6,  10, 112,  13],
       [114,  15,   6, 110]])

In [57]:
a.reshape([4,3])

array([[ 12,   3,   4],
       [  5,   6,  10],
       [112,  13, 114],
       [ 15,   6, 110]])

In [58]:
a.reshape([6,2])

array([[ 12,   3],
       [  4,   5],
       [  6,  10],
       [112,  13],
       [114,  15],
       [  6, 110]])

In [59]:
a.reshape([1,12])

array([[ 12,   3,   4,   5,   6,  10, 112,  13, 114,  15,   6, 110]])

In [60]:
a.reshape([1,3,4])

array([[[ 12,   3,   4,   5],
        [  6,  10, 112,  13],
        [114,  15,   6, 110]]])

In [61]:
a=np.array([[12,3,4,5,6,10],[112,13,114,15,6,110]])
a

array([[ 12,   3,   4,   5,   6,  10],
       [112,  13, 114,  15,   6, 110]])

In [62]:
a.resize([3,4])

In [63]:
a

array([[ 12,   3,   4,   5],
       [  6,  10, 112,  13],
       [114,  15,   6, 110]])

# flattening:
- reshape(-1): shalow
- ravel(): shalow
- flatten(): deep

In [64]:
a=np.array([[[[12,3,4,5,6,10],[112,13,114,15,6,110]]]])
a

array([[[[ 12,   3,   4,   5,   6,  10],
         [112,  13, 114,  15,   6, 110]]]])

In [65]:
a1=a.reshape(-1)
a1

array([ 12,   3,   4,   5,   6,  10, 112,  13, 114,  15,   6, 110])

In [66]:
a1[-1]=1000

In [67]:
a1

array([  12,    3,    4,    5,    6,   10,  112,   13,  114,   15,    6,
       1000])

In [68]:
a

array([[[[  12,    3,    4,    5,    6,   10],
         [ 112,   13,  114,   15,    6, 1000]]]])

In [69]:
a=np.array([[[[12,3,4,5,6,10],[112,13,114,15,6,110]]]])
a

array([[[[ 12,   3,   4,   5,   6,  10],
         [112,  13, 114,  15,   6, 110]]]])

In [70]:
a1=a.ravel()
a1

array([ 12,   3,   4,   5,   6,  10, 112,  13, 114,  15,   6, 110])

In [71]:
a1[-2]=60

In [72]:
a1

array([ 12,   3,   4,   5,   6,  10, 112,  13, 114,  15,  60, 110])

In [73]:
a

array([[[[ 12,   3,   4,   5,   6,  10],
         [112,  13, 114,  15,  60, 110]]]])

In [74]:
a=np.array([[[[12,3,4,5,6,10],[112,13,114,15,6,110]]]])
a

array([[[[ 12,   3,   4,   5,   6,  10],
         [112,  13, 114,  15,   6, 110]]]])

In [75]:
a1=a.flatten()
a1

array([ 12,   3,   4,   5,   6,  10, 112,  13, 114,  15,   6, 110])

In [76]:
a1[-1]=100
a1

array([ 12,   3,   4,   5,   6,  10, 112,  13, 114,  15,   6, 100])

In [77]:
a

array([[[[ 12,   3,   4,   5,   6,  10],
         [112,  13, 114,  15,   6, 110]]]])

# matrix vs array:

- matrix at most 2d while array could of n dimension
- product of matrix treats diiferent 

In [78]:
a1=np.mat([[1,1,1],[2,3,5],[3,0,10]])
a2=np.mat([[10,10,1],[20,30,5],[0,0,10]])
print(a1)
print(a2)

[[ 1  1  1]
 [ 2  3  5]
 [ 3  0 10]]
[[10 10  1]
 [20 30  5]
 [ 0  0 10]]


In [79]:
a1*a2

matrix([[ 30,  40,  16],
        [ 80, 110,  67],
        [ 30,  30, 103]])

In [80]:
a1=np.array([[1,1,1],[2,3,5],[3,0,10]])
a2=np.array([[10,10,1],[20,30,5],[0,0,10]])
print(a1)
print(a2)
print("\n")
a1*a2

[[ 1  1  1]
 [ 2  3  5]
 [ 3  0 10]]
[[10 10  1]
 [20 30  5]
 [ 0  0 10]]




array([[ 10,  10,   1],
       [ 40,  90,  25],
       [  0,   0, 100]])

# trace: sum of diagonal elements

In [81]:
a1=np.array([[1,1,1],[2,3,5],[3,0,10]])

In [82]:
a1

array([[ 1,  1,  1],
       [ 2,  3,  5],
       [ 3,  0, 10]])

In [83]:
np.trace(a1)

14

# diag: 
- it fetches the diagonal element
- it creates the array of diogonal elements

In [84]:
a1

array([[ 1,  1,  1],
       [ 2,  3,  5],
       [ 3,  0, 10]])

In [85]:
np.diag(a1)

array([ 1,  3, 10])

In [86]:
np.diag(a1,k=1)

array([1, 5])

In [87]:
np.diag(a1,k=-1)

array([2, 0])

In [88]:
a1

array([[ 1,  1,  1],
       [ 2,  3,  5],
       [ 3,  0, 10]])

In [89]:
np.diag([12,3,4,56,7,8,10])

array([[12,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0],
       [ 0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0, 56,  0,  0,  0],
       [ 0,  0,  0,  0,  7,  0,  0],
       [ 0,  0,  0,  0,  0,  8,  0],
       [ 0,  0,  0,  0,  0,  0, 10]])

# transpose

In [90]:
a1

array([[ 1,  1,  1],
       [ 2,  3,  5],
       [ 3,  0, 10]])

In [91]:
a1.T

array([[ 1,  2,  3],
       [ 1,  3,  0],
       [ 1,  5, 10]])

In [92]:
a

array([[[[ 12,   3,   4,   5,   6,  10],
         [112,  13, 114,  15,   6, 110]]]])

# universal functions
- sum
- mean
- floor
- ceil
- sqrt
- argmax/argmin
- median

In [9]:
import numpy as np
a=np.array([[24,34.5,12,1],[36,3.4,6,0]])
a

array([[24. , 34.5, 12. ,  1. ],
       [36. ,  3.4,  6. ,  0. ]])

In [10]:
np.sum(a)

116.9

In [11]:
np.mean(a)

14.6125

In [12]:
np.median(a)

9.0

In [13]:
np.max(a)

36.0

In [14]:
np.min(a)

0.0

In [15]:
np.max(a,axis=1)

array([34.5, 36. ])

In [16]:
a

array([[24. , 34.5, 12. ,  1. ],
       [36. ,  3.4,  6. ,  0. ]])

In [17]:
np.min(a,axis=1)

array([1., 0.])

In [18]:
np.min(a,axis=0)

array([24. ,  3.4,  6. ,  0. ])

In [19]:
np.sum(a,axis=1)

array([71.5, 45.4])

In [20]:
np.argmax(a)

4

In [21]:
a

array([[24. , 34.5, 12. ,  1. ],
       [36. ,  3.4,  6. ,  0. ]])

In [22]:
np.floor(a)

array([[24., 34., 12.,  1.],
       [36.,  3.,  6.,  0.]])

In [23]:
np.ceil(a)

array([[24., 35., 12.,  1.],
       [36.,  4.,  6.,  0.]])

In [24]:
np.sqrt(a)

array([[4.89897949, 5.87367006, 3.46410162, 1.        ],
       [6.        , 1.84390889, 2.44948974, 0.        ]])

# element wise operations

In [25]:
a1=np.array([[12,3,4,5],[1,2,1,10]])
a2=np.array([[2,2,10,10],[1,2,0,10]])
a1

array([[12,  3,  4,  5],
       [ 1,  2,  1, 10]])

In [26]:
a2

array([[ 2,  2, 10, 10],
       [ 1,  2,  0, 10]])

In [27]:
a1+a2

array([[14,  5, 14, 15],
       [ 2,  4,  1, 20]])

In [28]:
a1-a2

array([[10,  1, -6, -5],
       [ 0,  0,  1,  0]])

In [29]:
a1/a2

C:\Users\HP\AppData\Local\Temp\ipykernel_312\3705041958.py:1: RuntimeWarning: divide by zero encountered in divide
  a1/a2


array([[6. , 1.5, 0.4, 0.5],
       [1. , 1. , inf, 1. ]])

In [30]:
a1+4

array([[16,  7,  8,  9],
       [ 5,  6,  5, 14]])

In [31]:
a1>3

array([[ True, False,  True,  True],
       [False, False, False,  True]])

In [32]:
a1.shape

(2, 4)

In [33]:
a2.shape

(2, 4)

# broadcasting: It is the technique by which we can perform element wise operation on the arrays having different shape  provided they met some criteria

In [34]:
a1=np.array([[12,14],[90,34]])
a2=np.array([[34,1],[23,4]])
print(a1.shape)
print(a2.shape)
a1+a2

(2, 2)
(2, 2)


array([[ 46,  15],
       [113,  38]])

In [35]:
a1=np.array([[12,14],[90,34]])
a2=np.array([[34,1,3],[23,4,4]])
print(a1.shape)
print(a2.shape)
a1+a2

(2, 2)
(2, 3)


ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

# case 1 : when dimension is same, if either of dimension size is 1, then corresponding value is to be matched with opposite value

In [36]:
a1=np.array([[12,14],[90,34]])
a2=np.array([[34,1]])
print(a1.shape)
print(a2.shape)
a1+a2

(2, 2)
(1, 2)


array([[ 46,  15],
       [124,  35]])

In [37]:
a1=np.array([[12,14,4],[90,34,4]])
a2=np.array([[34,1]])
print(a1.shape)
print(a2.shape)
a1+a2

(2, 3)
(1, 2)


ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [38]:
a1=np.array([[12,14],[90,34]])
a2=np.array([[34,1,3]])
print(a1.shape)
print(a2.shape)
a1+a2

(2, 2)
(1, 3)


ValueError: operands could not be broadcast together with shapes (2,2) (1,3) 

# case 2: when dimension is different

In [39]:
a=np.array([[[12,13],[89,90],[90,10]]])
print(a.shape)
a1=np.array([[10,10],[90,10]])
print(a1.shape)
a+a1

(1, 3, 2)
(2, 2)


ValueError: operands could not be broadcast together with shapes (1,3,2) (2,2) 

In [40]:
a=np.array([[[12,13,1],[89,90,1],[0,2,1]]])
print(a.shape)
a1=np.array([[10,10,1],[90,10,1],[1,1,1]])
print(a1.shape)
a+a1

(1, 3, 3)
(3, 3)


array([[[ 22,  23,   2],
        [179, 100,   2],
        [  1,   3,   2]]])

# random

# generate the random value from 0 to 1

In [53]:
np.random.seed(12) # seed is used to lock the random value # pass any number in ()
np.random.random()

0.15416284237967237

# generate a  random  value from specified range

In [42]:
np.random.uniform(2,50)

37.522385432739426

# generate a  random  value in int from specified range

In [43]:
np.random.randint(2,50)

4

# mutiple values

In [44]:
np.random.randint(2,50,10)

array([ 5,  5, 14, 24,  7, 15, 27, 36, 13, 12])

# create an array of shape 2,5 where the elements lies from 2 to 20

In [45]:
np.random.randint(2,20,10).reshape(2,5)

array([[ 2, 10, 14, 15,  5],
       [ 6,  5,  3,  2, 18]])

In [46]:
np.random.randint(2,20,[2,5])

array([[ 8, 15, 11, 15, 18],
       [ 2, 16, 17,  3,  6]])

# randomly choose

In [47]:
l=["card1","card2","card3","card4"]
np.random.shuffle(l)

In [48]:
l

['card3', 'card2', 'card4', 'card1']

In [49]:
np.random.choice(l)

'card1'

# guess the number game

In [50]:
print("lets play the game ..welcome user !!!")
print("guess the number from 1 to 100")
sys=np.random.randint(1,100)
print(sys)
while(True):
    user=int(input("guess the number "))
    if user==sys:
        print("won")
        break
    else:
        if sys<user:
            print("guess the number lower side")
        else:
            print("guess the number higher side ")
        continue

lets play the game ..welcome user !!!
guess the number from 1 to 100
45


guess the number  6


guess the number higher side 


guess the number  7


guess the number higher side 


guess the number  7


guess the number higher side 


guess the number  8


guess the number higher side 


guess the number  9


guess the number higher side 


guess the number  0


guess the number higher side 


guess the number  6


guess the number higher side 


guess the number  8


guess the number higher side 


guess the number  45


won


In [51]:
print("lets play the game ..welcome user !!!")
print("guess the number from 1 to 100")
sys=np.random.randint(1,100)
print(sys)
attempt=1
while(attempt<6):
    user=int(input("guess the number "))
    if user==sys:
        print("won","at atttempt    ",attempt)
        break
    else:
        if sys<user:
            print("guess the number lower side")
        else:
            print("guess the number higher side ")
        attempt=attempt+1
        if attempt==6:
            print("u cross the limit")
            break
        continue

lets play the game ..welcome user !!!
guess the number from 1 to 100
38


guess the number  56


guess the number lower side


guess the number  78


guess the number lower side


guess the number  90


guess the number lower side


guess the number  2


guess the number higher side 


guess the number  3


guess the number higher side 
u cross the limit


# stone paper sciessor

In [2]:
import numpy as np
import pandas as pd

# Define the choices
choices = ['Stone', 'Paper', 'Scissors']

# Define the rules as a dictionary
rules = {
    'Stone': 'Scissors',  # Stone beats Scissors
    'Scissors': 'Paper',  # Scissors beats Paper
    'Paper': 'Stone'      # Paper beats Stone
}

# Function to determine the winner
def determine_winner(player, computer):
    if player == computer:
        return 'Draw'
    elif rules[player] == computer:
        return 'Player'
    else:
        return 'Computer'

# Function to play the game
def play_game(rounds=1):
    results = []

    for _ in range(rounds):
        # Player's choice
        player_choice = input("Enter your choice (Stone, Paper, Scissors): ").capitalize()
        while player_choice not in choices:
            print("Invalid choice. Please choose again.")
            player_choice = input("Enter your choice (Stone, Paper, Scissors): ").capitalize()
        
        # Computer's choice
        computer_choice = np.random.choice(choices)
        
        # Determine the winner
        winner = determine_winner(player_choice, computer_choice)
        
        # Append the result
        results.append({
            'Player Choice': player_choice,
            'Computer Choice': computer_choice,
            'Winner': winner
        })
        
        # Provide immediate feedback
        print(f"Player chose {player_choice}, Computer chose {computer_choice}.")
        if winner == 'Draw':
            print("It's a draw!")
        else:
            print(f"The winner is: {winner}")
        print()
    
    # Convert results to DataFrame
    results_df = pd.DataFrame(results)
    return results_df

# Main function to run the interactive game
if __name__ == "__main__":
    num_rounds = int(input("Enter the number of rounds you want to play: "))
    game_results = play_game(num_rounds)
    print("\nGame Summary:")
    print(game_results)


Enter the number of rounds you want to play:  5
Enter your choice (Stone, Paper, Scissors):  paper


Player chose Paper, Computer chose Scissors.
The winner is: Computer



Enter your choice (Stone, Paper, Scissors):  stone


Player chose Stone, Computer chose Stone.
It's a draw!



Enter your choice (Stone, Paper, Scissors):  stone


Player chose Stone, Computer chose Scissors.
The winner is: Player



Enter your choice (Stone, Paper, Scissors):  sd


Invalid choice. Please choose again.


Enter your choice (Stone, Paper, Scissors):  paper


Player chose Paper, Computer chose Stone.
The winner is: Player



Enter your choice (Stone, Paper, Scissors):  paper


Player chose Paper, Computer chose Stone.
The winner is: Player


Game Summary:
  Player Choice Computer Choice    Winner
0         Paper        Scissors  Computer
1         Stone           Stone      Draw
2         Stone        Scissors    Player
3         Paper           Stone    Player
4         Paper           Stone    Player
